    export default {
        body: document.querySelector ('body'),
        categorieList: document.querySelector('.categories'),
        productsList: document.querySelector('.products'),
        notFound: document.querySelector('.not-found'),
        loadMore: document.querySelector('.load-more-btn'),
        productListLoader: document.querySelector('[product-list-loader]'),
        modal: document.querySelector('.modal'),
        closeModal: document.querySelector('.modal__close-btn'),
        modalProduct: document.querySelector('.modal-product'),
        searchForm: document.querySelector('form.search-form'),
        clearButton: document.querySelector('button.search-form__btn-clear'),
        modalLoader: document.querySelector('[modal-loader]'),
        modalBtnWishlist: document.querySelector('.modal-product__btn--wishlist'),
        modalBtnAddToCart: document.querySelector('.modal-product__btn--cart'),
        wishlistLength: document.querySelector('[data-wishlist-count]'),
        cartLength: document.querySelector('[data-cart-count]'),
        cartItems: document.querySelector('[data-count]'),
        totalPrice: document.querySelector('[data-price]'),
        shippingPrice: document.querySelector('[data-shipping]'),
        scrollUpBtn: document.querySelector('.scroll-top-btn'),
        buyProductsBtn: document.querySelector('.cart-summary__btn'),
        checkoutModal: document.querySelector('.checkout-modal'),
        closeCheckoutModalBtn: document.querySelector('.checkout-modal__close'),
        checkoutPrice: document.querySelector('[data-checkout-price]'),
        checkoutShipping: document.querySelector('[data-checkout-shipping]'),
        checkoutTotal: document.querySelector('[data-checkout-total]'),
        checkoutSummary: document.querySelector('.checkout__summary'),
        checkoutForm: document.querySelector('.checkout-form'),
        checkoutSuccess: document.querySelector('.checkout-success'),
        orderNumber: document.querySelector('[data-order-number]'),
        continueShoppingBtn: document.querySelector('.checkout-success__btn'),
        themeToggleBtn: document.querySelector('.theme-toggle-btn')
    }

